INSERT INTO _countries (country_id, title_ru, title_en) VALUES (7, 'Грузия', 'Georgia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (126, 'Мексика', 'Mexico');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (35, 'Белиз', 'Belize');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (29, 'Аруба', 'Aruba');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (47, 'Бутан', 'Bhutan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (73, 'Дания', 'Denmark');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (130, 'Монголия', 'Mongolia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (129, 'Монако', 'Monaco');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (57, 'Гаити', 'Haiti');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (85, 'Ирландия', 'Ireland');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (120, 'Мали', 'Mali');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (100, 'Конго', 'Congo');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (72, 'Гуам', 'Guam');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (25, 'Ангола', 'Angola');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (104, 'Куба', 'Cuba');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (106, 'Лаос', 'Laos');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (110, 'Ливия', 'Libya');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (60, 'Гана', 'Ghana');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (59, 'Гамбия', 'Gambia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (36, 'Бельгия', 'Belgium');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (37, 'Бенин', 'Benin');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (231, 'Джибути', 'Djibouti');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (95, 'Кипр', 'Cyprus');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (15, 'Молдова', 'Moldova');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (12, 'Латвия', 'Latvia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (88, 'Италия', 'Italy');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (97, 'Китай', 'China');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (77, 'Замбия', 'Zambia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (63, 'Гвинея', 'Guinea');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (116, 'Макао', 'Macau');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (80, 'Индия', 'India');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (94, 'Кения', 'Kenya');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (118, 'Малави', 'Malawi');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (58, 'Гайана', 'Guyana');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (89, 'Йемен', 'Yemen');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (93, 'Катар', 'Qatar');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (119, 'Малайзия', 'Malaysia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (99, 'Коморы', 'Comoros');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (113, 'Маврикий', 'Mauritius');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (132, 'Мьянма', 'Myanmar');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (65, 'Германия', 'Germany');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (134, 'Науру', 'Nauru');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (135, 'Непал', 'Nepal');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (233, 'Ватикан', 'Vatican');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (201, 'Уганда', 'Uganda');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (14, 'Эстония', 'Estonia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (182, 'Сингапур', 'Singapore');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (228, 'Ямайка', 'Jamaica');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (136, 'Нигер', 'Niger');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (1, 'Россия', 'Russia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (140, 'Никарагуа', 'Nicaragua');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (224, 'Эфиопия', 'Ethiopia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (181, 'Сербия', 'Serbia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (56, 'Габон', 'Gabon');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (200, 'Турция', 'Turkey');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (188, 'Судан', 'Sudan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (31, 'Багамы', 'Bahamas');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (141, 'Ниуэ', 'Niue');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (194, 'Того', 'Togo');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (212, 'Хорватия', 'Croatia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (34, 'Бахрейн', 'Bahrain');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (191, 'Таиланд', 'Thailand');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (187, 'Сомали', 'Somalia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (153, 'Палау', 'Palau');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (195, 'Токелау', 'Tokelau');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (209, 'Франция', 'France');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (207, 'Финляндия', 'Finland');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (8, 'Израиль', 'Israel');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (220, 'Шри-Ланка', 'Sri Lanka');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (167, 'Самоа', 'Samoa');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (176, 'Сенегал', 'Senegal');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (171, 'Свазиленд', 'Swaziland');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (38, 'Бермуды', 'Bermuda');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (185, 'Словения', 'Slovenia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (192, 'Тайвань', 'Taiwan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (216, 'Чили', 'Chile');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (9, 'США', 'USA');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (205, 'Фиджи', 'Fiji');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (198, 'Тувалу', 'Tuvalu');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (144, 'Норвегия', 'Norway');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (164, 'Руанда', 'Rwanda');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (214, 'Чад', 'Chad');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (147, 'Остров Мэн', 'Isle of Man');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (146, 'Оман', 'Oman');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (155, 'Панама', 'Panama');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (158, 'Перу', 'Peru');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (163, 'Реюньон', 'Réunion');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (221, 'Эквадор', 'Ecuador');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (11, 'Кыргызстан', 'Kyrgyzstan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (84, 'Иран', 'Iran');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (175, 'Сейшелы', 'Seychelles');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (123, 'Марокко', 'Morocco');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (90, 'Кабо-Верде', 'Cape Verde');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (74, 'Доминика', 'Dominica');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (149, 'Острова Кайман', 'Cayman Islands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (79, 'Зимбабве', 'Zimbabwe');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (170, 'Саудовская Аравия', 'Saudi Arabia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (69, 'Гренада', 'Grenada');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (131, 'Монтсеррат', 'Montserrat');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (122, 'Мальта', 'Malta');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (16, 'Таджикистан', 'Tajikistan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (203, 'Уругвай', 'Uruguay');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (4, 'Казахстан', 'Kazakhstan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (199, 'Тунис', 'Tunisia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (10, 'Канада', 'Canada');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (54, 'Восточный Тимор', 'East Timor');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (24, 'Ангилья', 'Anguilla');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (196, 'Тонга', 'Tonga');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (81, 'Индонезия', 'Indonesia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (234, 'Синт-Мартен', 'Sint Maarten');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (128, 'Мозамбик', 'Mozambique');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (39, 'Болгария', 'Bulgaria');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (82, 'Иордания', 'Jordan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (71, 'Греция', 'Greece');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (108, 'Либерия', 'Liberia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (184, 'Словакия', 'Slovakia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (102, 'Коста-Рика', 'Costa Rica');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (165, 'Румыния', 'Romania');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (133, 'Намибия', 'Namibia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (107, 'Лесото', 'Lesotho');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (117, 'Македония', 'Macedonia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (68, 'Гонконг', 'Hong Kong');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (109, 'Ливан', 'Lebanon');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (137, 'Нигерия', 'Nigeria');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (193, 'Танзания', 'Tanzania');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (197, 'Тринидад и Тобаго', 'Trinidad and Tobago');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (62, 'Гватемала', 'Guatemala');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (152, 'Пакистан', 'Pakistan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (103, 'Кот д`Ивуар', 'Côte d`Ivoire');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (229, 'Япония', 'Japan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (5, 'Азербайджан', 'Azerbaijan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (66, 'Гибралтар', 'Gibraltar');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (78, 'Западная Сахара', 'Western Sahara');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (124, 'Мартиника', 'Martinique');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (18, 'Узбекистан', 'Uzbekistan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (50, 'Венгрия', 'Hungary');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (112, 'Люксембург', 'Luxembourg');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (206, 'Филиппины', 'Philippines');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (43, 'Бразилия', 'Brazil');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (87, 'Испания', 'Spain');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (202, 'Уоллис и Футуна', 'Wallis and Futuna');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (20, 'Австрия', 'Austria');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (114, 'Мавритания', 'Mauritania');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (30, 'Афганистан', 'Afghanistan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (13, 'Литва', 'Lithuania');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (3, 'Беларусь', 'Belarus');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (217, 'Швейцария', 'Switzerland');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (143, 'Новая Каледония', 'New Caledonia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (138, 'Кюрасао', 'Curaçao');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (204, 'Фарерские острова', 'Faroe Islands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (17, 'Туркменистан', 'Turkmenistan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (40, 'Боливия', 'Bolivia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (156, 'Папуа - Новая Гвинея', 'Papua New Guinea');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (186, 'Соломоновы Острова', 'Solomon Islands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (49, 'Великобритания', 'United Kingdom');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (115, 'Мадагаскар', 'Madagascar');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (222, 'Экваториальная Гвинея', 'Equatorial Guinea');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (92, 'Камерун', 'Cameroon');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (44, 'Бруней-Даруссалам', 'Brunei Darussalam');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (2, 'Украина', 'Ukraine');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (230, 'Черногория', 'Montenegro');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (190, 'Сьерра-Леоне', 'Sierra Leone');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (166, 'Сальвадор', 'El Salvador');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (142, 'Новая Зеландия', 'New Zealand');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (183, 'Сирийская Арабская Республика', 'Syria');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (210, 'Французская Гвиана', 'French Guiana');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (19, 'Австралия', 'Australia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (26, 'Андорра', 'Andorra');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (51, 'Венесуэла', 'Venezuela');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (145, 'Объединенные Арабские Эмираты', 'United Arab Emirates');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (168, 'Сан-Марино', 'San Marino');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (64, 'Гвинея-Бисау', 'Guinea-Bissau');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (32, 'Бангладеш', 'Bangladesh');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (42, 'Ботсвана', 'Botswana');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (21, 'Албания', 'Albania');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (70, 'Гренландия', 'Greenland');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (232, 'Южный Судан', 'South Sudan');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (173, 'Северная Корея', 'North Korea');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (148, 'Остров Норфолк', 'Norfolk Island');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (53, 'Виргинские острова, США', 'US Virgin Islands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (67, 'Гондурас', 'Honduras');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (75, 'Доминиканская Республика', 'Dominican Republic');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (61, 'Гваделупа', 'Guadeloupe');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (105, 'Кувейт', 'Kuwait');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (213, 'Центрально-Африканская Республика', 'Central African Republic');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (174, 'Северные Марианские острова', 'Northern Mariana Islands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (215, 'Чехия', 'Czech Republic');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (139, 'Нидерланды', 'Netherlands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (52, 'Виргинские острова, Британские', 'British Virgin Islands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (169, 'Сан-Томе и Принсипи', 'São Tomé and Príncipe');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (46, 'Бурунди', 'Burundi');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (189, 'Суринам', 'Suriname');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (150, 'Острова Кука', 'Cook Islands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (172, 'Святая Елена', 'Saint Helena');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (178, 'Сент-Китс и Невис', 'Saint Kitts and Nevis');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (208, 'Фолклендские острова', 'Falkland Islands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (48, 'Вануату', 'Vanuatu');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (226, 'Южная Корея', 'South Korea');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (227, 'Южно-Африканская Республика', 'South Africa');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (55, 'Вьетнам', 'Vietnam');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (101, 'Конго, демократическая республика', 'Congo, Democratic Republic');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (76, 'Египет', 'Egypt');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (96, 'Кирибати', 'Kiribati');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (162, 'Пуэрто-Рико', 'Puerto Rico');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (223, 'Эритрея', 'Eritrea');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (211, 'Французская Полинезия', 'French Polynesia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (151, 'Острова Теркс и Кайкос', 'Turks and Caicos Islands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (157, 'Парагвай', 'Paraguay');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (160, 'Польша', 'Poland');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (177, 'Сент-Винсент', 'Saint Vincent and the Grenadines');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (154, 'Палестинская автономия', 'Palestine');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (219, 'Шпицберген и Ян Майен', 'Svalbard and Jan Mayen');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (22, 'Алжир', 'Algeria');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (33, 'Барбадос', 'Barbados');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (45, 'Буркина-Фасо', 'Burkina Faso');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (98, 'Колумбия', 'Colombia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (86, 'Исландия', 'Iceland');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (121, 'Мальдивы', 'Maldives');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (125, 'Маршалловы Острова', 'Marshall Islands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (127, 'Микронезия, федеративные штаты', 'Micronesia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (159, 'Питкерн', 'Pitcairn Islands');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (180, 'Сент-Пьер и Микелон', 'Saint Pierre and Miquelon');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (218, 'Швеция', 'Sweden');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (23, 'Американское Самоа', 'American Samoa');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (27, 'Антигуа и Барбуда', 'Antigua and Barbuda');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (28, 'Аргентина', 'Argentina');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (6, 'Армения', 'Armenia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (91, 'Камбоджа', 'Cambodia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (235, 'Бонайре, Синт-Эстатиус и Саба', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (161, 'Португалия', 'Portugal');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (179, 'Сент-Люсия', 'Saint Lucia');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (41, 'Босния и Герцеговина', 'Bosnia and Herzegovina');
INSERT INTO _countries (country_id, title_ru, title_en) VALUES (111, 'Лихтенштейн', 'Liechtenstein');
